### ISSUE TITLE
cpupower

### ISSUE THREAD

**Issue by Vrtak-CZ** [nodefourtytwo/gnome-shell-extension-cpu-freq#1]
cpufreq now called cpupower see: https://wiki.archlinux.org/index.php/Cpufreq#cpupower

**Comment by nodefourtytwo** [comment]
Thanks for the info! How did I miss it? I'll update the code to allow the use of both cpupower and cpufreq depending on which one is installed.

**Comment by Vrtak-CZ** [comment]
any news?

**Comment by nodefourtytwo** [comment]
Yes, it's more complicated than I thought.

cpupower doesn't give any quick tool to read the frequency or the available governors as cpufreq-info did.

I don't have much time to work on it yet, so any patch is more than welcome.

**Comment by victornoel** [comment]
Hi, I don't get it, why don't you use cpupower frequency-info -g ?
There is a bunch of options to frequency-info that would give you the data you want in a simple format…

Am I wrong?

**Comment by LeCoyote** [comment]
FWIW, I'm in the process of adapting your extension so that it can use cpupower. I'll get back to you soon.

**Comment by LeCoyote** [comment]
It's done. I'll fork and upload my changes.

**Comment by nodefourtytwo** [comment]
Awesome! Thanks.

I started working on it yesterday evening with victornoel info, but I really lack of time. So I welcome gladly contributions.

**Comment by LeCoyote** [comment]
No problem :) Also, the readme should probably be edited to reflect the fact that we don't depend on cpufreq-info anymore.

**Comment by nodefourtytwo** [comment]
It's been added so I close the bug
