### ISSUE TITLE
cpu scaling not work?

### ISSUE THREAD

**Issue by claudio1983** [nodefourtytwo/gnome-shell-extension-cpu-freq#16]
I'm having a problem.
I can not select the frequency of my processor.
I have the program installed cpufreq-selector and gnome-applets
In "gnome 3 fallback" can select any frequency of my processor, but does not work in "default" gnome 3
I wonder how can I enable the selection of the processor frequency in gnome 3.

Debian 7.1.0, Gnome 3.4

cat /proc/cpuinfo 
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 15
model name  : Intel(R) Pentium(R) Dual  CPU  T2370  @ 1.73GHz
stepping    : 13
microcode   : 0xa1
cpu MHz     : 1333.000
cache size  : 1024 KB
physical id : 0
siblings    : 2
core id     : 0
cpu cores   : 2
apicid      : 0
initial apicid  : 0
fdiv_bug    : no
hlt_bug     : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 10
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm
bogomips    : 3467.08
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor   : 1
vendor_id   : GenuineIntel
cpu family  : 6
model       : 15
model name  : Intel(R) Pentium(R) Dual  CPU  T2370  @ 1.73GHz
stepping    : 13
microcode   : 0xa1
cpu MHz     : 1333.000
cache size  : 1024 KB
physical id : 0
siblings    : 2
core id     : 1
cpu cores   : 2
apicid      : 1
initial apicid  : 1
fdiv_bug    : no
hlt_bug     : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 10
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm
bogomips    : 3466.58
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

Thank you for your attention
- sorry, my English is not good, I say pt_BR

**Comment by nodefourtytwo** [comment]
Typing cpufreq-info in the command line should give you a list of available governors(ex: conservative, ondemand,...).

Once you see which are available, you can try to set the governor with cpufreq-selector, ex:
cpufreq-selector -c 1 -g conservative

it should tell you if anything is wrong, in which case, you should refer to your distribution documentation.

Good luck.

**Comment by claudio1983** [comment]
with the command line can change the cpufreq governor smoothly. But I would be able to choose the frequency of my processor by extension cpufreq.

Here'm using "gnome fallback" where I can select the frequency that I desire.
Screenshot gnome fallback
![cpufreq2](https://f.cloud.github.com/assets/5104955/874473/fc2ccbd4-f88b-11e2-9ec7-8109677e27e6.jpg)

However the extension cpufreq not give me that option.
Screenshot gnome 3 with extension cpufreq
![cpufre](https://f.cloud.github.com/assets/5104955/874478/085e2cae-f88c-11e2-8fdb-1ac198e26d02.jpg)

I would select the frequency of my processor using the extension cpufreq but without being in fallback mode, it is possible?
