### ISSUE TITLE
Errors during execution

### ISSUE THREAD

**Issue by victornoel** [nodefourtytwo/gnome-shell-extension-cpu-freq#3]
Hi,

I get from time to time an error in looking glass saying:
TypeError: indicator is null

I also get another one saying:
Error: Expected type utf8 for Argument 'text' but got type 'undefined' (nil)

**Comment by nodefourtytwo** [comment]
Looking glass doesn't make debug really easy... I hope they'll include a line number for it some day, or make a proper debugger.

I don't really see how indicator could be null. It's only set to null when the extension is disabled. Do you disable it?

**Comment by victornoel** [comment]
Hmm, well… I don't have any more of these errors in my log, so maybe it was old errors for when the extension wasn't working before cpupower… I will check during the day and if nothing happen I will close the bug :)

**Comment by nodefourtytwo** [comment]
No news and I don't reproduce it here.

Should I close?

**Comment by victornoel** [comment]
Ho right, sorry, I completely forgot :)
