### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by victornoel** [nodefourtytwo/gnome-shell-extension-cpu-freq#5]
Hi,

Not a very important bug, but well, warnings are there for that :)

I get that in the logs:

```
JS ERROR: !!!   WARNING: 'assignment to undeclared variable governoractual'
JS ERROR: !!!   WARNING: file '/home/victor/.local/share/gnome-shell/extensions/cpufreq@nodefourtytwo.net/extension.js' line 107 exception 0 number 156
```

Thanks

**Comment by gliptak** [comment]
I'm seeing this WARNING too. Thanks

**Comment by nodefourtytwo** [comment]
I still can't reproduce it, can you tell me if it still happens with the last version?

**Comment by victornoel** [comment]
Well yes, I just upgraded it, rebooted to be sure everything was cleanly started without any dirtystate left before the upgrade and I got that error:
    JS ERROR: !!!   WARNING: 'assignment to undeclared variable governoractual'
    JS ERROR: !!!   WARNING: file '/home/victor/.local/share/gnome-shell/extensions/cpufreq@nodefourtytwo.net/extension.js' line 123 exception 0 number 156

Note that it actually does not bother me at all, but still, that's strange :)
