### ISSUE TITLE
Celeron M - type processor question

### ISSUE THREAD

**Issue by 0x0ade** [nodefourtytwo/gnome-shell-extension-cpu-freq#6]
I am having problems with Celeron M - type processors, I heard they mostly can't handle voltage / mhz scaling. 
cpufreq-info will yell something about cpufreq-drivers not found. In the BIOS there is no way to over-/underclock the CPU.

Is there still a way to do it? And how?

Using:
Ubuntu 12.10 on Wubi 12.04
Intel Celeron M 900
eMachines E525 
BIOS manually updated to 3.10 per Gateway support site

**Comment by nodefourtytwo** [comment]
Not the best place to ask, but try to do:
sudo modprobe acpi_cpufreq
and then cpufreq-info again.

**Comment by 0x0ade** [comment]
I know it isn't, I googl'd all the time. I also tried that, without success. I tought you can help because you made the plugin and maybe are knowing how to set up cpufreq on various CPUs.

**Comment by nodefourtytwo** [comment]
Sorry it did not work. It can be because you're using ubuntu in Wubi. Or because your CPU doesn't support it.

**Comment by 0x0ade** [comment]
:/ Still thanks. Wubi links HDD calls to a virtual HDD as far as I know so it can't be caused by it so I think my CPU doesn't support it (had luck that the Linux kernel in Ubuntu STILL supports the Celeron M900, most of other Celerons do not work)
