### ISSUE TITLE
not working in fedora 18

### ISSUE THREAD

**Issue by rdrms** [nodefourtytwo/gnome-shell-extension-cpu-freq#8]
I have cpufreq-selector installed, but the extension will not install.  It clicks on, asks for authorization, then turns itself off.  This happened on Ubuntu when I didn't have cpufreq-utils installed.

**Comment by bubi-luka** [comment]
@ryanrms : where did you get cpufreq-selector?
@nodefourtytwo : any update on fedora 18 issues?

**Comment by nodefourtytwo** [comment]
Sorry guys, I don't have any Fedora installed.

Try this and give the output here: 
which cpufreq-info
which cpupower
which cpufreq-selector

Also look at the error outputs of the extension in Looking Glass (Alt+F2 lg), tab extensions.

**Comment by bubi-luka** [comment]
$ which cpufreq-selector 
/usr/bin/cpufreq-selector

$ which cpupower
/usr/bin/which: no cpupower in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin)

$ which cpufreq-info
/usr/bin/which: no cpufreq-info in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin)

## 

After clicking install on extensions.gnome.org the extension tries to install. I have it in my Looking Glass, status Disabled. There are no errors emitted by this extension shown in the LG.

**Comment by nodefourtytwo** [comment]
Your problem is having neither cpufreq-info nor cpupower. You should install the one recommended by your distribution.

**Comment by bubi-luka** [comment]
Since Fedora 18 does not have neither cpufreq-info not cpupower package available I did not know where to get them and tought cpufreq-selector should be sufficient.
Now I have found that package kernel-tools contains cpupower. After installation cpu-freq installs and works as expected. Thanks for quick reply.
Before closing the issue there would be nice to get some info from @ryanrms, as it is not necessary his original problem is the same as mine.

**Comment by nodefourtytwo** [comment]
I also leave it open so the extension does not crash and becomes more verbose if these utilities are missing.

**Comment by Feanturo** [comment]
Hi.
With Fedora 18 and standard cpupower package, the problem with me is that it can detect the different governors, however it cannot set them.
Working line commands are : cpupower frequency-set --governor [Governor]
In case that could help.

**Comment by nodefourtytwo** [comment]
The problem with the cpupower frequency-set command line is that it requires to be root.

That's why I use the tool cpufreq-selector that has the ability to work for users, granted that you give the user the authorization with policykit.

I could not come up with a better solution yet.

**Comment by gregor2005** [comment]
does anybody find the the polkit conf under fedora 18. polkit is installed but the path didn't exists also under /etc/security there are no files that look like the given example from the readme

**Comment by ghost** [comment]
in fedora the cpufreq-selector is in the gnome-applets package.  Do 'yum install gnome-applets'

**Comment by gregor2005** [comment]
thx

**Comment by pstarek** [comment]
Hi all,

I have found a solution for policykit in Fedora 18.

Create a file /usr/share/polkit-1/rules.d/cpufreq-shell-extension.rules  with this content:

polkit.addRule(function(action, subject) {
    if (action.id == "org.gnome.cpufreqselector" &&
        subject.local &&
        subject.active &&
        subject.isInGroup ("wheel")) {
            return polkit.Result.YES;
        }
});

And users in wheel group be able to change governor without need to enter password.

**Comment by mikhailramalho** [comment]
You can also place the rule file under /etc/polkit-1/rules.d/ and it also worked.

To add your user to the wheel group, run:

usermod -a -G wheel YYYYY

where YYYYY  is your user.
